### ISSUE TITLE
Payments list doesn't contain the full list of all items for some accounts

### ISSUE THREAD

**Issue by Cheaternl** [bunqCommunity/bunqDesktop#394]
The history of some of my accounts do not go further than February this year.  The Bunq android app DO show me that there is history before February for that particular account.

This fact of incomplete history, leads to the fact that the 'Total change' is incorrect.

**Comment by Crecket** [comment]
The total change calculation was changed and hopefully fixed so if you're using the production build than this should be fixed in dev

**Comment by Cheaternl** [comment]
I use version 0.9.1. Downloaded and installed (and tested) before experiencing this issue and reporting this ticket.

**Comment by Cheaternl** [comment]
Also the title of this Github issue, is a bit misleading, because I know the incomplete list of payments, is the cause of an incorrect total change amount.

**Comment by Cheaternl** [comment]
I installed version [Nightly build 2018-11-01 23:41:01] but that didn't fix anything for me.

**Comment by Crecket** [comment]
On the nightly build it might look inaccurate if your entire account isn't fully loaded but I'll look into what is going wrong. It is correct for my personal account but it still seems to bug out in some situations

**Comment by Crecket** [comment]
Actually looking into this again, this might simply be caused by the hardcoded limit of 1000 events per type. Your account likely has more than 1000 "regular" payment types so it won't show anything more than that right now. 

So this is not a bug but a "feature" 😅 Closing this for now since you should be able to set the event limit to a higher number or disable it completely on the next release
